Marks and (debugger) functionality
flow-storm/flow-storm-debugger pull request #190
Opened 2024-12-10 21:47 UTC by rafd

- Inject `(debugger)` and `(breakpoint)` macros to clojure.core (they behave the same)
- When flowstorm encounters either of these, it tracks a "mark"
- Marks are displayed in the UI

<img width="512" alt="Screenshot 2024-12-10 at 16 37 02" src="https://github.com/user-attachments/assets/c3fc496d-b5d5-4daa-82a4-7e7f53dfeb26">

- The UI will navigate to the first mark encountered (unless an Exception was already navigated to)

-------

Potentially changes/improvements:
 - merge this with existing "bookmark" functionality (ie. this would be a programmatic way to add bookmarks); potentially instead of `debugger` or `breakpoint`, we just call the macro `bookmark`
 - support passing a label to differentiate different marks
 - make macro handle a single arg transparently to allow use inside of threading macros
   ```clojure 
    (->> data 
         (map first) 
         bookmark 
         (apply +))
    ```
- when displaying marks in the mark list, provide a bit more context (ns + fn)

2024-12-11 11:27 UTC, jpmonettas commented
Great! I like the idea of reusing the bookmarks functionality, and I think the changes should be pretty easy.
I think they are to : 
- Make `expression-mark-event` call `dbg-state/add-bookmark` instead and keep  the auto jumping code
- Remove the marks stuff from state
- Remove the marks dropdown code

Maybe we can call the macros `debugger` and `bookmark`? 
I like the `debugger` one also because it provides a similar behavior to the js one in the sense that it will "jump there", so it is not only about adding a bookmark.

As part of this PR I would add support for the macros to optionally receive a label, which can be used as the bookmark text.
For this we would need to change the macros to expand to symbols with meta instead of keywords, so they can carry extra info.

What do you think?

2024-12-11 21:57 UTC, jpmonettas requested changes
I like where this is going, thanks. Added a couple of comments.

2024-12-11 22:40 UTC, rafd commented
Changes since my last note:
 - reworked "marks" to re-use the pre-existing bookmarks functionality, including supporting passing a label
 - also show source of a bookmark (ui  or api) in the bookmarks combo and bookmarks window

<img width="1434" alt="Screenshot 2024-12-11 at 17 33 32" src="https://github.com/user-attachments/assets/ecb5cdcb-6ba9-4b27-836b-a663ef507577" />

I will undo the changes to the bookmarks data structure, and I can remove the combo box.

2024-12-12 01:22 UTC, rafd commented on src-dbg/flow_storm/debugger/ui/flows/screen.clj
> +        bookmarks-menu-data (ui/menu-button
Removed

2024-12-12 01:23 UTC, rafd commented on src-dbg/flow_storm/debugger/state.clj
> +  (swap! state assoc-in [:bookmarks flow-id [flow-id thread-id idx]] bookmark))
Reverted to one level.

2024-12-12 01:25 UTC, rafd commented
- Removed the bookmarks-combo
- Reverted bookmark state storage change

When merging this in, I recommend a squash merge.

2024-12-12 12:05 UTC, jpmonettas approved these changes

2024-12-12 12:06 UTC, merged